# argo/argo-cd. nginx Ingress 뒤 lab용 insecure.
server:
  replicas: 1
  insecure: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.nginx.lab.origemite.com

redis-ha:
  enabled: false

controller:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  replicas: 1

dex:
  enabled: false

notifications:
  enabled: false
