apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      nodeSelector:
        lab.origemite.com/workload: kafka
      containers:
        - name: kafka
          image: apache/kafka:3.7.0
          ports:
            - name: internal
              containerPort: 9092
            - name: external
              containerPort: 19092
          envFrom:
            - configMapRef:
                name: kafka-config
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: internal
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: internal
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
